python3: can't open file '/work/mech-ai/bella/MolTransformer_repo/mains.py': [Errno 2] No such file or directory
